-- =====================================================================================
-- Permission catalogue and system roles (SECURITY.md §4.2, §4.3).
-- GENERATED from docs/SECURITY.md; PermissionCatalogIntegrationTest verifies that the database
-- catalogue equals the document and the permission constants in code. Idempotent.
-- Permissions are never deleted: codes no longer listed get deprecated_at.
-- =====================================================================================

INSERT INTO auth.permissions (code, module, description, is_sensitive) VALUES
  ('auth.user.read', 'auth', 'Read user', false),
  ('auth.user.manage', 'auth', 'Manage user', false),
  ('auth.role.read', 'auth', 'Read role', false),
  ('auth.role.manage', 'auth', 'Manage role', true),
  ('auth.role_assignment.manage', 'auth', 'Manage role assignment', true),
  ('auth.service_account.manage', 'auth', 'Manage service account', false),
  ('auth.api_token.manage_own', 'auth', 'Manage own api token', false),
  ('admin.audit.read', 'admin', 'Read audit', false),
  ('admin.audit.read_global', 'admin', 'Read global audit', false),
  ('admin.settings.manage', 'admin', 'Manage settings', false),
  ('admin.system.read', 'admin', 'Read system', false),
  ('org.company.create', 'org', 'Create company', false),
  ('org.company.manage', 'org', 'Manage company', false),
  ('org.branch.read', 'org', 'Read branch', false),
  ('org.branch.manage', 'org', 'Manage branch', false),
  ('org.department.read', 'org', 'Read department', false),
  ('org.department.manage', 'org', 'Manage department', false),
  ('org.exchange_rate.read', 'org', 'Read exchange rate', false),
  ('org.exchange_rate.manage', 'org', 'Manage exchange rate', false),
  ('org.exchange_rate.override', 'org', 'Override exchange rate', false),
  ('org.tax_code.read', 'org', 'Read tax code', false),
  ('org.tax_code.manage', 'org', 'Manage tax code', false),
  ('org.payment_terms.read', 'org', 'Read payment terms', false),
  ('org.payment_terms.manage', 'org', 'Manage payment terms', false),
  ('partners.partner.read', 'partners', 'Read partner', false),
  ('partners.partner.manage', 'partners', 'Manage partner', false),
  ('partners.partner.read_bank', 'partners', 'Read bank partner', true),
  ('partners.partner.manage_bank', 'partners', 'Manage bank partner', true),
  ('partners.customer.manage', 'partners', 'Manage customer', false),
  ('partners.supplier.manage', 'partners', 'Manage supplier', false),
  ('inventory.product.read', 'inventory', 'Read product', false),
  ('inventory.product.manage', 'inventory', 'Manage product', false),
  ('inventory.warehouse.read', 'inventory', 'Read warehouse', false),
  ('inventory.warehouse.manage', 'inventory', 'Manage warehouse', false),
  ('inventory.stock.read', 'inventory', 'Read stock', false),
  ('inventory.valuation.read', 'inventory', 'Read valuation', false),
  ('inventory.movement.read', 'inventory', 'Read movement', false),
  ('inventory.movement.create', 'inventory', 'Create movement', false),
  ('inventory.movement.post', 'inventory', 'Post movement', false),
  ('inventory.movement.reverse', 'inventory', 'Reverse movement', false),
  ('inventory.adjustment.manage', 'inventory', 'Manage adjustment', false),
  ('inventory.adjustment.approve', 'inventory', 'Approve adjustment', false),
  ('inventory.count.manage', 'inventory', 'Manage count', false),
  ('inventory.count.post', 'inventory', 'Post count', false),
  ('inventory.settings.manage', 'inventory', 'Manage settings', false),
  ('procurement.requisition.read', 'procurement', 'Read requisition', false),
  ('procurement.requisition.create', 'procurement', 'Create requisition', false),
  ('procurement.requisition.approve', 'procurement', 'Approve requisition', false),
  ('procurement.purchase_order.read', 'procurement', 'Read purchase order', false),
  ('procurement.purchase_order.create', 'procurement', 'Create purchase order', false),
  ('procurement.purchase_order.approve', 'procurement', 'Approve purchase order', false),
  ('procurement.purchase_order.approve_high', 'procurement', 'Approve high purchase order', false),
  ('procurement.purchase_order.cancel', 'procurement', 'Cancel purchase order', false),
  ('procurement.purchase_order.close', 'procurement', 'Close purchase order', false),
  ('procurement.receipt.read', 'procurement', 'Read receipt', false),
  ('procurement.receipt.create', 'procurement', 'Create receipt', false),
  ('procurement.receipt.post', 'procurement', 'Post receipt', false),
  ('procurement.return.manage', 'procurement', 'Manage return', false),
  ('procurement.supplier_bill.read', 'procurement', 'Read supplier bill', false),
  ('procurement.supplier_bill.create', 'procurement', 'Create supplier bill', false),
  ('procurement.supplier_bill.create_direct', 'procurement', 'Create direct supplier bill', false),
  ('procurement.supplier_bill.post', 'procurement', 'Post supplier bill', false),
  ('procurement.supplier_bill.override_match', 'procurement', 'Override match supplier bill', false),
  ('procurement.settings.manage', 'procurement', 'Manage settings', false),
  ('sales.price_list.read', 'sales', 'Read price list', false),
  ('sales.price_list.manage', 'sales', 'Manage price list', false),
  ('sales.quotation.read', 'sales', 'Read quotation', false),
  ('sales.quotation.manage', 'sales', 'Manage quotation', false),
  ('sales.order.read', 'sales', 'Read order', false),
  ('sales.order.create', 'sales', 'Create order', false),
  ('sales.order.confirm', 'sales', 'Confirm order', false),
  ('sales.order.override_credit', 'sales', 'Override credit order', false),
  ('sales.order.override_price', 'sales', 'Override price order', false),
  ('sales.order.discount_high', 'sales', 'Discount high order', false),
  ('sales.order.cancel', 'sales', 'Cancel order', false),
  ('sales.order.close', 'sales', 'Close order', false),
  ('sales.delivery.read', 'sales', 'Read delivery', false),
  ('sales.delivery.create', 'sales', 'Create delivery', false),
  ('sales.delivery.post', 'sales', 'Post delivery', false),
  ('sales.return.manage', 'sales', 'Manage return', false),
  ('sales.invoice.read', 'sales', 'Read invoice', false),
  ('sales.invoice.create', 'sales', 'Create invoice', false),
  ('sales.invoice.create_direct', 'sales', 'Create direct invoice', false),
  ('sales.invoice.post', 'sales', 'Post invoice', false),
  ('sales.invoice.send', 'sales', 'Send invoice', false),
  ('sales.settings.manage', 'sales', 'Manage settings', false),
  ('accounting.account.read', 'accounting', 'Read account', false),
  ('accounting.account.manage', 'accounting', 'Manage account', false),
  ('accounting.account_mapping.manage', 'accounting', 'Manage account mapping', false),
  ('accounting.fiscal_year.manage', 'accounting', 'Manage fiscal year', false),
  ('accounting.fiscal_year.close', 'accounting', 'Close fiscal year', false),
  ('accounting.period.read', 'accounting', 'Read period', false),
  ('accounting.period.soft_close', 'accounting', 'Soft close period', false),
  ('accounting.period.close', 'accounting', 'Close period', false),
  ('accounting.period.reopen', 'accounting', 'Reopen period', true),
  ('accounting.period.post_soft_closed', 'accounting', 'Post soft closed period', false),
  ('accounting.journal.manage', 'accounting', 'Manage journal', false),
  ('accounting.journal_entry.read', 'accounting', 'Read journal entry', false),
  ('accounting.journal_entry.create', 'accounting', 'Create journal entry', false),
  ('accounting.journal_entry.post', 'accounting', 'Post journal entry', false),
  ('accounting.journal_entry.reverse', 'accounting', 'Reverse journal entry', false),
  ('accounting.ar.read', 'accounting', 'Read ar', false),
  ('accounting.ap.read', 'accounting', 'Read ap', false),
  ('accounting.bank_account.read', 'accounting', 'Read bank account', false),
  ('accounting.bank_account.manage', 'accounting', 'Manage bank account', false),
  ('accounting.payment.read', 'accounting', 'Read payment', false),
  ('accounting.payment.create', 'accounting', 'Create payment', false),
  ('accounting.payment.post', 'accounting', 'Post payment', false),
  ('accounting.payment.void', 'accounting', 'Void payment', true),
  ('accounting.payment.allocate', 'accounting', 'Allocate payment', false),
  ('accounting.payment.unallocate', 'accounting', 'Unallocate payment', false),
  ('accounting.expense.read', 'accounting', 'Read expense', false),
  ('accounting.expense.create', 'accounting', 'Create expense', false),
  ('accounting.expense.post', 'accounting', 'Post expense', false),
  ('accounting.bank_reconciliation.manage', 'accounting', 'Manage bank reconciliation', false),
  ('accounting.report.read', 'accounting', 'Read report', false),
  ('accounting.settings.manage', 'accounting', 'Manage settings', false),
  ('hr.employee.read', 'hr', 'Read employee', false),
  ('hr.employee.manage', 'hr', 'Manage employee', false),
  ('hr.employee.read_sensitive', 'hr', 'Read sensitive employee', true),
  ('hr.employee.manage_bank', 'hr', 'Manage bank employee', true),
  ('hr.employee.terminate', 'hr', 'Terminate employee', false),
  ('hr.position.manage', 'hr', 'Manage position', false),
  ('hr.leave.read', 'hr', 'Read leave', false),
  ('hr.leave.approve', 'hr', 'Approve leave', false),
  ('hr.leave.adjust', 'hr', 'Adjust leave', false),
  ('hr.leave.configure', 'hr', 'Configure leave', false),
  ('payroll.configuration.manage', 'payroll', 'Manage configuration', true),
  ('payroll.compensation.read', 'payroll', 'Read compensation', true),
  ('payroll.compensation.manage', 'payroll', 'Manage compensation', true),
  ('payroll.run.read', 'payroll', 'Read run', true),
  ('payroll.run.prepare', 'payroll', 'Prepare run', true),
  ('payroll.run.approve', 'payroll', 'Approve run', true),
  ('payroll.run.post', 'payroll', 'Post run', true),
  ('payroll.run.pay', 'payroll', 'Pay run', true),
  ('payroll.payslip.read', 'payroll', 'Read payslip', true),
  ('payroll.report.read', 'payroll', 'Read report', true),
  ('reporting.sales.read', 'reporting', 'Read sales', false),
  ('reporting.procurement.read', 'reporting', 'Read procurement', false),
  ('reporting.inventory.read', 'reporting', 'Read inventory', false),
  ('reporting.hr.read', 'reporting', 'Read hr', false),
  ('reporting.export.create', 'reporting', 'Create export', false),
  ('reporting.saved_report.share', 'reporting', 'Share saved report', false)
ON CONFLICT (code) DO UPDATE SET module = EXCLUDED.module, description = EXCLUDED.description,
  is_sensitive = EXCLUDED.is_sensitive, deprecated_at = NULL;

UPDATE auth.permissions SET deprecated_at = now()
WHERE deprecated_at IS NULL AND code NOT IN (
  'auth.user.read',
  'auth.user.manage',
  'auth.role.read',
  'auth.role.manage',
  'auth.role_assignment.manage',
  'auth.service_account.manage',
  'auth.api_token.manage_own',
  'admin.audit.read',
  'admin.audit.read_global',
  'admin.settings.manage',
  'admin.system.read',
  'org.company.create',
  'org.company.manage',
  'org.branch.read',
  'org.branch.manage',
  'org.department.read',
  'org.department.manage',
  'org.exchange_rate.read',
  'org.exchange_rate.manage',
  'org.exchange_rate.override',
  'org.tax_code.read',
  'org.tax_code.manage',
  'org.payment_terms.read',
  'org.payment_terms.manage',
  'partners.partner.read',
  'partners.partner.manage',
  'partners.partner.read_bank',
  'partners.partner.manage_bank',
  'partners.customer.manage',
  'partners.supplier.manage',
  'inventory.product.read',
  'inventory.product.manage',
  'inventory.warehouse.read',
  'inventory.warehouse.manage',
  'inventory.stock.read',
  'inventory.valuation.read',
  'inventory.movement.read',
  'inventory.movement.create',
  'inventory.movement.post',
  'inventory.movement.reverse',
  'inventory.adjustment.manage',
  'inventory.adjustment.approve',
  'inventory.count.manage',
  'inventory.count.post',
  'inventory.settings.manage',
  'procurement.requisition.read',
  'procurement.requisition.create',
  'procurement.requisition.approve',
  'procurement.purchase_order.read',
  'procurement.purchase_order.create',
  'procurement.purchase_order.approve',
  'procurement.purchase_order.approve_high',
  'procurement.purchase_order.cancel',
  'procurement.purchase_order.close',
  'procurement.receipt.read',
  'procurement.receipt.create',
  'procurement.receipt.post',
  'procurement.return.manage',
  'procurement.supplier_bill.read',
  'procurement.supplier_bill.create',
  'procurement.supplier_bill.create_direct',
  'procurement.supplier_bill.post',
  'procurement.supplier_bill.override_match',
  'procurement.settings.manage',
  'sales.price_list.read',
  'sales.price_list.manage',
  'sales.quotation.read',
  'sales.quotation.manage',
  'sales.order.read',
  'sales.order.create',
  'sales.order.confirm',
  'sales.order.override_credit',
  'sales.order.override_price',
  'sales.order.discount_high',
  'sales.order.cancel',
  'sales.order.close',
  'sales.delivery.read',
  'sales.delivery.create',
  'sales.delivery.post',
  'sales.return.manage',
  'sales.invoice.read',
  'sales.invoice.create',
  'sales.invoice.create_direct',
  'sales.invoice.post',
  'sales.invoice.send',
  'sales.settings.manage',
  'accounting.account.read',
  'accounting.account.manage',
  'accounting.account_mapping.manage',
  'accounting.fiscal_year.manage',
  'accounting.fiscal_year.close',
  'accounting.period.read',
  'accounting.period.soft_close',
  'accounting.period.close',
  'accounting.period.reopen',
  'accounting.period.post_soft_closed',
  'accounting.journal.manage',
  'accounting.journal_entry.read',
  'accounting.journal_entry.create',
  'accounting.journal_entry.post',
  'accounting.journal_entry.reverse',
  'accounting.ar.read',
  'accounting.ap.read',
  'accounting.bank_account.read',
  'accounting.bank_account.manage',
  'accounting.payment.read',
  'accounting.payment.create',
  'accounting.payment.post',
  'accounting.payment.void',
  'accounting.payment.allocate',
  'accounting.payment.unallocate',
  'accounting.expense.read',
  'accounting.expense.create',
  'accounting.expense.post',
  'accounting.bank_reconciliation.manage',
  'accounting.report.read',
  'accounting.settings.manage',
  'hr.employee.read',
  'hr.employee.manage',
  'hr.employee.read_sensitive',
  'hr.employee.manage_bank',
  'hr.employee.terminate',
  'hr.position.manage',
  'hr.leave.read',
  'hr.leave.approve',
  'hr.leave.adjust',
  'hr.leave.configure',
  'payroll.configuration.manage',
  'payroll.compensation.read',
  'payroll.compensation.manage',
  'payroll.run.read',
  'payroll.run.prepare',
  'payroll.run.approve',
  'payroll.run.post',
  'payroll.run.pay',
  'payroll.payslip.read',
  'payroll.report.read',
  'reporting.sales.read',
  'reporting.procurement.read',
  'reporting.inventory.read',
  'reporting.hr.read',
  'reporting.export.create',
  'reporting.saved_report.share');

INSERT INTO auth.roles (code, name, description, is_system, requires_mfa) VALUES
  ('COMPANY_ADMIN', 'Company administrator', 'System role (SECURITY.md §4.3)', true, true),
  ('AUDITOR', 'Auditor (read-only)', 'System role (SECURITY.md §4.3)', true, false),
  ('WAREHOUSE_CLERK', 'Warehouse clerk', 'System role (SECURITY.md §4.3)', true, false),
  ('INVENTORY_MANAGER', 'Inventory manager', 'System role (SECURITY.md §4.3)', true, false),
  ('BUYER', 'Buyer', 'System role (SECURITY.md §4.3)', true, false),
  ('PROCUREMENT_MANAGER', 'Procurement manager', 'System role (SECURITY.md §4.3)', true, false),
  ('SALES_REP', 'Sales representative', 'System role (SECURITY.md §4.3)', true, false),
  ('SALES_MANAGER', 'Sales manager', 'System role (SECURITY.md §4.3)', true, false),
  ('BILLING_CLERK', 'Billing clerk', 'System role (SECURITY.md §4.3)', true, false),
  ('AR_CLERK', 'Accounts receivable clerk', 'System role (SECURITY.md §4.3)', true, false),
  ('AP_CLERK', 'Accounts payable clerk', 'System role (SECURITY.md §4.3)', true, true),
  ('ACCOUNTANT', 'Accountant', 'System role (SECURITY.md §4.3)', true, true),
  ('FINANCIAL_CONTROLLER', 'Financial controller', 'System role (SECURITY.md §4.3)', true, true),
  ('HR_OFFICER', 'HR officer', 'System role (SECURITY.md §4.3)', true, false),
  ('HR_MANAGER', 'HR manager', 'System role (SECURITY.md §4.3)', true, true),
  ('PAYROLL_OFFICER', 'Payroll officer', 'System role (SECURITY.md §4.3)', true, true),
  ('PAYROLL_APPROVER', 'Payroll approver', 'System role (SECURITY.md §4.3)', true, true),
  ('EMPLOYEE', 'Employee (self-service)', 'System role (SECURITY.md §4.3)', true, false)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description,
  is_system = true, requires_mfa = EXCLUDED.requires_mfa, updated_at = now(), version = auth.roles.version + 1;

-- System role permissions are owned by this migration: replace them as a whole.
DELETE FROM auth.role_permissions rp USING auth.roles r WHERE rp.role_id = r.id AND r.is_system;

INSERT INTO auth.role_permissions (role_id, permission_code)
SELECT r.id, v.permission_code FROM (VALUES
  ('COMPANY_ADMIN', 'accounting.settings.manage'),
  ('COMPANY_ADMIN', 'admin.audit.read'),
  ('COMPANY_ADMIN', 'auth.role_assignment.manage'),
  ('COMPANY_ADMIN', 'inventory.settings.manage'),
  ('COMPANY_ADMIN', 'org.branch.manage'),
  ('COMPANY_ADMIN', 'org.branch.read'),
  ('COMPANY_ADMIN', 'org.company.manage'),
  ('COMPANY_ADMIN', 'org.department.manage'),
  ('COMPANY_ADMIN', 'org.department.read'),
  ('COMPANY_ADMIN', 'org.exchange_rate.manage'),
  ('COMPANY_ADMIN', 'org.exchange_rate.override'),
  ('COMPANY_ADMIN', 'org.exchange_rate.read'),
  ('COMPANY_ADMIN', 'org.payment_terms.manage'),
  ('COMPANY_ADMIN', 'org.payment_terms.read'),
  ('COMPANY_ADMIN', 'org.tax_code.manage'),
  ('COMPANY_ADMIN', 'org.tax_code.read'),
  ('COMPANY_ADMIN', 'procurement.settings.manage'),
  ('COMPANY_ADMIN', 'sales.settings.manage'),
  ('AUDITOR', 'accounting.account.read'),
  ('AUDITOR', 'accounting.ap.read'),
  ('AUDITOR', 'accounting.ar.read'),
  ('AUDITOR', 'accounting.bank_account.read'),
  ('AUDITOR', 'accounting.expense.read'),
  ('AUDITOR', 'accounting.journal_entry.read'),
  ('AUDITOR', 'accounting.payment.read'),
  ('AUDITOR', 'accounting.period.read'),
  ('AUDITOR', 'accounting.report.read'),
  ('AUDITOR', 'admin.audit.read'),
  ('AUDITOR', 'hr.employee.read'),
  ('AUDITOR', 'hr.leave.read'),
  ('AUDITOR', 'inventory.movement.read'),
  ('AUDITOR', 'inventory.product.read'),
  ('AUDITOR', 'inventory.stock.read'),
  ('AUDITOR', 'inventory.valuation.read'),
  ('AUDITOR', 'inventory.warehouse.read'),
  ('AUDITOR', 'org.branch.read'),
  ('AUDITOR', 'org.department.read'),
  ('AUDITOR', 'org.exchange_rate.read'),
  ('AUDITOR', 'org.payment_terms.read'),
  ('AUDITOR', 'org.tax_code.read'),
  ('AUDITOR', 'partners.partner.read'),
  ('AUDITOR', 'procurement.purchase_order.read'),
  ('AUDITOR', 'procurement.receipt.read'),
  ('AUDITOR', 'procurement.requisition.read'),
  ('AUDITOR', 'procurement.supplier_bill.read'),
  ('AUDITOR', 'reporting.hr.read'),
  ('AUDITOR', 'reporting.inventory.read'),
  ('AUDITOR', 'reporting.procurement.read'),
  ('AUDITOR', 'reporting.sales.read'),
  ('AUDITOR', 'sales.delivery.read'),
  ('AUDITOR', 'sales.invoice.read'),
  ('AUDITOR', 'sales.order.read'),
  ('AUDITOR', 'sales.price_list.read'),
  ('AUDITOR', 'sales.quotation.read'),
  ('WAREHOUSE_CLERK', 'inventory.count.manage'),
  ('WAREHOUSE_CLERK', 'inventory.movement.create'),
  ('WAREHOUSE_CLERK', 'inventory.movement.post'),
  ('WAREHOUSE_CLERK', 'inventory.movement.read'),
  ('WAREHOUSE_CLERK', 'inventory.product.read'),
  ('WAREHOUSE_CLERK', 'inventory.stock.read'),
  ('WAREHOUSE_CLERK', 'inventory.warehouse.read'),
  ('WAREHOUSE_CLERK', 'procurement.purchase_order.read'),
  ('WAREHOUSE_CLERK', 'procurement.receipt.create'),
  ('WAREHOUSE_CLERK', 'procurement.receipt.post'),
  ('WAREHOUSE_CLERK', 'procurement.receipt.read'),
  ('WAREHOUSE_CLERK', 'sales.delivery.create'),
  ('WAREHOUSE_CLERK', 'sales.delivery.post'),
  ('WAREHOUSE_CLERK', 'sales.delivery.read'),
  ('WAREHOUSE_CLERK', 'sales.order.read'),
  ('INVENTORY_MANAGER', 'inventory.adjustment.approve'),
  ('INVENTORY_MANAGER', 'inventory.adjustment.manage'),
  ('INVENTORY_MANAGER', 'inventory.count.manage'),
  ('INVENTORY_MANAGER', 'inventory.count.post'),
  ('INVENTORY_MANAGER', 'inventory.movement.create'),
  ('INVENTORY_MANAGER', 'inventory.movement.post'),
  ('INVENTORY_MANAGER', 'inventory.movement.read'),
  ('INVENTORY_MANAGER', 'inventory.movement.reverse'),
  ('INVENTORY_MANAGER', 'inventory.product.manage'),
  ('INVENTORY_MANAGER', 'inventory.product.read'),
  ('INVENTORY_MANAGER', 'inventory.stock.read'),
  ('INVENTORY_MANAGER', 'inventory.valuation.read'),
  ('INVENTORY_MANAGER', 'inventory.warehouse.manage'),
  ('INVENTORY_MANAGER', 'inventory.warehouse.read'),
  ('INVENTORY_MANAGER', 'procurement.purchase_order.read'),
  ('INVENTORY_MANAGER', 'procurement.receipt.create'),
  ('INVENTORY_MANAGER', 'procurement.receipt.post'),
  ('INVENTORY_MANAGER', 'procurement.receipt.read'),
  ('INVENTORY_MANAGER', 'reporting.inventory.read'),
  ('INVENTORY_MANAGER', 'sales.delivery.create'),
  ('INVENTORY_MANAGER', 'sales.delivery.post'),
  ('INVENTORY_MANAGER', 'sales.delivery.read'),
  ('INVENTORY_MANAGER', 'sales.order.read'),
  ('BUYER', 'inventory.product.read'),
  ('BUYER', 'inventory.stock.read'),
  ('BUYER', 'partners.partner.read'),
  ('BUYER', 'partners.supplier.manage'),
  ('BUYER', 'procurement.purchase_order.create'),
  ('BUYER', 'procurement.purchase_order.read'),
  ('BUYER', 'procurement.receipt.read'),
  ('BUYER', 'procurement.requisition.create'),
  ('BUYER', 'procurement.requisition.read'),
  ('PROCUREMENT_MANAGER', 'inventory.product.read'),
  ('PROCUREMENT_MANAGER', 'inventory.stock.read'),
  ('PROCUREMENT_MANAGER', 'partners.partner.read'),
  ('PROCUREMENT_MANAGER', 'partners.supplier.manage'),
  ('PROCUREMENT_MANAGER', 'procurement.purchase_order.approve'),
  ('PROCUREMENT_MANAGER', 'procurement.purchase_order.approve_high'),
  ('PROCUREMENT_MANAGER', 'procurement.purchase_order.cancel'),
  ('PROCUREMENT_MANAGER', 'procurement.purchase_order.close'),
  ('PROCUREMENT_MANAGER', 'procurement.purchase_order.create'),
  ('PROCUREMENT_MANAGER', 'procurement.purchase_order.read'),
  ('PROCUREMENT_MANAGER', 'procurement.receipt.read'),
  ('PROCUREMENT_MANAGER', 'procurement.requisition.approve'),
  ('PROCUREMENT_MANAGER', 'procurement.requisition.create'),
  ('PROCUREMENT_MANAGER', 'procurement.requisition.read'),
  ('PROCUREMENT_MANAGER', 'procurement.return.manage'),
  ('PROCUREMENT_MANAGER', 'reporting.procurement.read'),
  ('SALES_REP', 'inventory.product.read'),
  ('SALES_REP', 'inventory.stock.read'),
  ('SALES_REP', 'partners.customer.manage'),
  ('SALES_REP', 'partners.partner.read'),
  ('SALES_REP', 'sales.order.confirm'),
  ('SALES_REP', 'sales.order.create'),
  ('SALES_REP', 'sales.order.read'),
  ('SALES_REP', 'sales.price_list.read'),
  ('SALES_REP', 'sales.quotation.manage'),
  ('SALES_REP', 'sales.quotation.read'),
  ('SALES_MANAGER', 'inventory.product.read'),
  ('SALES_MANAGER', 'inventory.stock.read'),
  ('SALES_MANAGER', 'partners.customer.manage'),
  ('SALES_MANAGER', 'partners.partner.read'),
  ('SALES_MANAGER', 'reporting.sales.read'),
  ('SALES_MANAGER', 'sales.order.cancel'),
  ('SALES_MANAGER', 'sales.order.close'),
  ('SALES_MANAGER', 'sales.order.confirm'),
  ('SALES_MANAGER', 'sales.order.create'),
  ('SALES_MANAGER', 'sales.order.discount_high'),
  ('SALES_MANAGER', 'sales.order.override_credit'),
  ('SALES_MANAGER', 'sales.order.override_price'),
  ('SALES_MANAGER', 'sales.order.read'),
  ('SALES_MANAGER', 'sales.price_list.manage'),
  ('SALES_MANAGER', 'sales.price_list.read'),
  ('SALES_MANAGER', 'sales.quotation.manage'),
  ('SALES_MANAGER', 'sales.quotation.read'),
  ('SALES_MANAGER', 'sales.return.manage'),
  ('BILLING_CLERK', 'accounting.ar.read'),
  ('BILLING_CLERK', 'sales.delivery.read'),
  ('BILLING_CLERK', 'sales.invoice.create'),
  ('BILLING_CLERK', 'sales.invoice.post'),
  ('BILLING_CLERK', 'sales.invoice.read'),
  ('BILLING_CLERK', 'sales.invoice.send'),
  ('BILLING_CLERK', 'sales.order.read'),
  ('AR_CLERK', 'accounting.ar.read'),
  ('AR_CLERK', 'accounting.bank_account.read'),
  ('AR_CLERK', 'accounting.payment.allocate'),
  ('AR_CLERK', 'accounting.payment.create'),
  ('AR_CLERK', 'accounting.payment.post'),
  ('AR_CLERK', 'accounting.payment.read'),
  ('AR_CLERK', 'partners.partner.read'),
  ('AR_CLERK', 'sales.invoice.read'),
  ('AP_CLERK', 'accounting.ap.read'),
  ('AP_CLERK', 'accounting.bank_account.read'),
  ('AP_CLERK', 'accounting.payment.allocate'),
  ('AP_CLERK', 'accounting.payment.create'),
  ('AP_CLERK', 'accounting.payment.post'),
  ('AP_CLERK', 'accounting.payment.read'),
  ('AP_CLERK', 'partners.partner.read'),
  ('AP_CLERK', 'partners.partner.read_bank'),
  ('AP_CLERK', 'procurement.supplier_bill.create'),
  ('AP_CLERK', 'procurement.supplier_bill.post'),
  ('AP_CLERK', 'procurement.supplier_bill.read'),
  ('ACCOUNTANT', 'accounting.account.manage'),
  ('ACCOUNTANT', 'accounting.account.read'),
  ('ACCOUNTANT', 'accounting.ap.read'),
  ('ACCOUNTANT', 'accounting.ar.read'),
  ('ACCOUNTANT', 'accounting.bank_account.manage'),
  ('ACCOUNTANT', 'accounting.bank_account.read'),
  ('ACCOUNTANT', 'accounting.bank_reconciliation.manage'),
  ('ACCOUNTANT', 'accounting.expense.create'),
  ('ACCOUNTANT', 'accounting.expense.post'),
  ('ACCOUNTANT', 'accounting.expense.read'),
  ('ACCOUNTANT', 'accounting.fiscal_year.manage'),
  ('ACCOUNTANT', 'accounting.journal.manage'),
  ('ACCOUNTANT', 'accounting.journal_entry.create'),
  ('ACCOUNTANT', 'accounting.journal_entry.post'),
  ('ACCOUNTANT', 'accounting.journal_entry.read'),
  ('ACCOUNTANT', 'accounting.journal_entry.reverse'),
  ('ACCOUNTANT', 'accounting.payment.allocate'),
  ('ACCOUNTANT', 'accounting.payment.create'),
  ('ACCOUNTANT', 'accounting.payment.post'),
  ('ACCOUNTANT', 'accounting.payment.read'),
  ('ACCOUNTANT', 'accounting.payment.unallocate'),
  ('ACCOUNTANT', 'accounting.period.post_soft_closed'),
  ('ACCOUNTANT', 'accounting.period.read'),
  ('ACCOUNTANT', 'accounting.period.soft_close'),
  ('ACCOUNTANT', 'accounting.report.read'),
  ('ACCOUNTANT', 'accounting.settings.manage'),
  ('ACCOUNTANT', 'procurement.purchase_order.read'),
  ('ACCOUNTANT', 'procurement.receipt.read'),
  ('ACCOUNTANT', 'procurement.requisition.read'),
  ('ACCOUNTANT', 'procurement.supplier_bill.read'),
  ('ACCOUNTANT', 'sales.delivery.read'),
  ('ACCOUNTANT', 'sales.invoice.read'),
  ('ACCOUNTANT', 'sales.order.read'),
  ('ACCOUNTANT', 'sales.price_list.read'),
  ('ACCOUNTANT', 'sales.quotation.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.account.manage'),
  ('FINANCIAL_CONTROLLER', 'accounting.account.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.account_mapping.manage'),
  ('FINANCIAL_CONTROLLER', 'accounting.ap.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.ar.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.bank_account.manage'),
  ('FINANCIAL_CONTROLLER', 'accounting.bank_account.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.bank_reconciliation.manage'),
  ('FINANCIAL_CONTROLLER', 'accounting.expense.create'),
  ('FINANCIAL_CONTROLLER', 'accounting.expense.post'),
  ('FINANCIAL_CONTROLLER', 'accounting.expense.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.fiscal_year.close'),
  ('FINANCIAL_CONTROLLER', 'accounting.fiscal_year.manage'),
  ('FINANCIAL_CONTROLLER', 'accounting.journal.manage'),
  ('FINANCIAL_CONTROLLER', 'accounting.journal_entry.create'),
  ('FINANCIAL_CONTROLLER', 'accounting.journal_entry.post'),
  ('FINANCIAL_CONTROLLER', 'accounting.journal_entry.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.journal_entry.reverse'),
  ('FINANCIAL_CONTROLLER', 'accounting.payment.allocate'),
  ('FINANCIAL_CONTROLLER', 'accounting.payment.create'),
  ('FINANCIAL_CONTROLLER', 'accounting.payment.post'),
  ('FINANCIAL_CONTROLLER', 'accounting.payment.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.payment.unallocate'),
  ('FINANCIAL_CONTROLLER', 'accounting.payment.void'),
  ('FINANCIAL_CONTROLLER', 'accounting.period.close'),
  ('FINANCIAL_CONTROLLER', 'accounting.period.post_soft_closed'),
  ('FINANCIAL_CONTROLLER', 'accounting.period.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.period.reopen'),
  ('FINANCIAL_CONTROLLER', 'accounting.period.soft_close'),
  ('FINANCIAL_CONTROLLER', 'accounting.report.read'),
  ('FINANCIAL_CONTROLLER', 'accounting.settings.manage'),
  ('FINANCIAL_CONTROLLER', 'org.exchange_rate.manage'),
  ('FINANCIAL_CONTROLLER', 'org.exchange_rate.override'),
  ('FINANCIAL_CONTROLLER', 'org.exchange_rate.read'),
  ('FINANCIAL_CONTROLLER', 'org.tax_code.manage'),
  ('FINANCIAL_CONTROLLER', 'org.tax_code.read'),
  ('FINANCIAL_CONTROLLER', 'partners.partner.manage_bank'),
  ('FINANCIAL_CONTROLLER', 'partners.partner.read'),
  ('FINANCIAL_CONTROLLER', 'procurement.supplier_bill.create_direct'),
  ('FINANCIAL_CONTROLLER', 'procurement.supplier_bill.override_match'),
  ('FINANCIAL_CONTROLLER', 'sales.invoice.create_direct'),
  ('HR_OFFICER', 'hr.employee.manage'),
  ('HR_OFFICER', 'hr.employee.read'),
  ('HR_OFFICER', 'hr.leave.adjust'),
  ('HR_OFFICER', 'hr.leave.approve'),
  ('HR_OFFICER', 'hr.leave.configure'),
  ('HR_OFFICER', 'hr.leave.read'),
  ('HR_OFFICER', 'hr.position.manage'),
  ('HR_MANAGER', 'hr.employee.manage'),
  ('HR_MANAGER', 'hr.employee.manage_bank'),
  ('HR_MANAGER', 'hr.employee.read'),
  ('HR_MANAGER', 'hr.employee.read_sensitive'),
  ('HR_MANAGER', 'hr.employee.terminate'),
  ('HR_MANAGER', 'hr.leave.adjust'),
  ('HR_MANAGER', 'hr.leave.approve'),
  ('HR_MANAGER', 'hr.leave.configure'),
  ('HR_MANAGER', 'hr.leave.read'),
  ('HR_MANAGER', 'hr.position.manage'),
  ('HR_MANAGER', 'reporting.hr.read'),
  ('PAYROLL_OFFICER', 'hr.employee.read'),
  ('PAYROLL_OFFICER', 'payroll.compensation.manage'),
  ('PAYROLL_OFFICER', 'payroll.compensation.read'),
  ('PAYROLL_OFFICER', 'payroll.configuration.manage'),
  ('PAYROLL_OFFICER', 'payroll.payslip.read'),
  ('PAYROLL_OFFICER', 'payroll.run.prepare'),
  ('PAYROLL_OFFICER', 'payroll.run.read'),
  ('PAYROLL_APPROVER', 'payroll.payslip.read'),
  ('PAYROLL_APPROVER', 'payroll.report.read'),
  ('PAYROLL_APPROVER', 'payroll.run.approve'),
  ('PAYROLL_APPROVER', 'payroll.run.pay'),
  ('PAYROLL_APPROVER', 'payroll.run.post'),
  ('PAYROLL_APPROVER', 'payroll.run.read')
) AS v (role_code, permission_code)
JOIN auth.roles r ON r.code = v.role_code;
